package es.um.pds.tarjetas.domain.model.entryHistorial.model;

//TODO Revisar si hay más tipos
public enum TipoEntryHistorial {
	TABLERO_CREADO, TABLERO_EDITADO, TABLERO_ELIMINADO, TABLERO_BLOQUEADO, TABLERO_DESBLOQUEADO, LISTA_CREADA,
	LISTA_EDITADA, LISTA_ELIMINADA, LIMITE_LISTA_CONFIGURADO, LISTA_ESPECIAL_DEFINIDA,
	PRERREQUISITOS_LISTA_CONFIGURADOS, TARJETA_CREADA, TARJETA_EDITADA, TARJETA_ELIMINADA, TARJETA_MOVIDA,
	TARJETA_COMPLETADA, TARJETA_ETIQUETADA, ETIQUETA_ELIMINADA, ETIQUETA_MODIFICADA
}
